# Generated by Django 5.1 on 2024-08-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
