# Generated by Django 5.1 on 2024-08-09 06:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0007_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoff_time', models.TimeField(default=django.utils.timezone.now)),
                ('work_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hrms.attendance')),
            ],
        ),
    ]
