# Generated by Django 5.1 on 2024-08-09 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_logoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logoff',
            name='work_hours',
        ),
        migrations.AlterField(
            model_name='logoff',
            name='logoff_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
