# Generated by Django 5.1 on 2024-08-09 08:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_remove_logoff_work_hours_alter_logoff_logoff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='logoff_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
