# Generated by Django 5.1 on 2024-08-09 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_attendance_logoff_time_alter_attendance_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='logoff_time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
