# Generated by Django 5.1 on 2024-08-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_taskgroup_groupmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_details', models.TextField()),
                ('deadline', models.DateField()),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_id', models.CharField(max_length=100)),
                ('members', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='leader',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='TaskGroup',
        ),
    ]
